"""4th Migration

Revision ID: 772b1a5b054c
Revises: 6f075852a5f6
Create Date: 2020-05-11 09:42:49.608448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772b1a5b054c'
down_revision = '6f075852a5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'timestamp')
    # ### end Alembic commands ###
